---
- name: Jenkins Server PHP dependences
  hosts: jenkins 
  become: yes
  tasks:

  - name: Jenkins Server PHP dependences
    apt:
      name: zip
      service: present

  - name: Jenkins Server PHP dependences
    apt:
      name: libapache2-mod-php
      service: present


  - name: Jenkins Server PHP dependences
    apt:
      name: phploc
      service: present


  - name: Jenkins Server PHP dependences
    apt:
      name: php-{xml,bcmath,bz2,intl,gd,mbstring,mysql,zip}
      service: present

  - name: Install composer
    shell: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    

  - name: Install composer
    shell: php -r "if (hash_file('sha384', 'composer-setup.php') === '906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" php composer-setup.php

  - name: Install composer
    shell: php -r "unlink('composer-setup.php');"
    
  