---
- name: Clear path /home/ubuntu
  become: yes
  file:
    path: /home/ubuntu/*
    state: absent

- name: Download artifactory
  become: yes
  get_url:
    url: https://releases.jfrog.io/artifactory/bintray-artifactory/org/artifactory/oss/jfrog-artifactory-oss/[RELEASE]/jfrog-artifactory-oss-[RELEASE]-linux.tar.gz
    dest: /home/ubuntu
    mode: 777

- name: Extract Artifactory
  become: yes
  ansible.builtin.unarchive:
    src: /home/ubuntu/jfrog-artifactory-oss-7.35.1-linux.tar.gz
    dest: /home/ubuntu/artifactory

- name: Run Artifactory
  become: yes
  command: /home/ubuntu/artifactory/artifactory/app/bin/artifactoryctl start

- name: Check the status
  become: yes
  command: /home/ubuntu/artifactory/artifactory/app/bin/artifactoryctl check
  notify: Test


#- name: Install Gnupg package
#  become: yes
#  remote_user: ubuntu
#  apt:
#    name: gnupg
#    state: present
#
#- name: Install net-tools package
#  become: yes
#  remote_user: ubuntu
#  apt:
#    name: net-tools
#    state: present
#
#
#- name: Install Artifactory
#  become: yes
#  command: dpkg -i /home/ubuntu/artifactory.deb
#  notify: Test
#  



#- name: Install Gnupg2 package
#  become: yes
# remote_user: ubuntu
# apt:
#   name: gnupg
#   state: present
#
#
#
# name: Download GPG key
# become: yes
# remote_user: ubuntu
# apt_key: 
#   url: https://api.bintray.com/orgs/jfrog/keys/gpg/public.key
#   state: present
#
# name: Add JFrog repo
# become: yes
# remote_user: ubuntu
# command: echo "deb https://jfrog.bintray.com/artifactory-debs bionic main" | tee /etc/apt/sources.list.d/jfrog.list
#
# name: Install jfrog
# become: yes
# apt:
#   update_cache: yes
#   name: jfrog-artifactory-oss
#   state: present
#
# name: state artifactory 
# become: yes
# service:
#   name: artifactory
#   state: restart
#   enable: yes
# notify: Test