pipeline {
  agent any
  stages {
    stage('Run Ansible Playbook') {
      steps {
        ansiblePlaybook(playbook: 'playbooks/site.yml', disableHostKeyChecking: true, vaultCredentialsId: '	Hlove', inventory: '${inventory}', tags: 'artifactory')
      }
    }

  }
  parameters {
    string(name: 'inventory', defaultValue: 'inventory/dev', description: 'This is the inventory file for the environment to deploy configuration')
  }
}