pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }

      }
    }

    stage('Test') {
      steps {
        sh '''echo "Testing Stage"
'''
      }
    }

  }
}