
-   name: Install httpd
    become: yes
    ansible.builtin.yum:
            name: httpd
            state: present
    
-   name: Install git
    become: yes
    ansible.builtin.git:
            name: git
            state: latest

-   name: Clone my repository
    become: yes
    ansible.builtin.git:
            repo: https://github.com/akingo7/tooling.git
            dest: /var/www/html
            force: yes

-   name: Copy /var/www/html/html to /var/www
    become: yes
    ansible.builtin.command: mv -r /var/www/html/html/ /var/www/

-   name: Check httpd status
    become: yes
    ansible.builtin.service:
            name: httpd
            state: started

-   name: Delete /var/www/html/html
    become: yes
    ansible.builtin.file:
            path: /var/www/html/html
            state: absent
            