
-   name: Install httpd
    become: yes
    tasks: 
        yum:
            name: httpd
            state: present
    
-   name: Install git
    become: yes
    tasks:
        git:
            name: git
            state: latest

-   name: Clone my repository
    become: yes
    tasks:
        git:
            repo: https://github.com/akingo7/tooling.git
            dest: /var/www/html
            force: yes

-   name: Copy /var/www/html/html to /var/www
    become: yes
    tasks:
        command: cp -R /var/www/html/html /var/www

-   name: Check httpd status
    become: yes
    tasks:
        service:
            name: httpd
            state: started

-   name: Delete /var/www/html/html
    become: yes
    tasks:
        file:
            path: /var/www/html/html
            state: absent
            