---
-   name: wireshark assignments
    import_playbook: ../static-assignments/common.yml
    
-   name: Import dynamic variables    
    import_playbook: .../dynamic-assignments/env-vars.yml
    task:
    - always

-   name: Webserver assignments 
    import_playbook: ../static-assignments/webserver