---
-   hosts: all
    name: Include dynamic variables
    import_playbook: 
    -   "../static-assignments/common.yml"
    -   "../dynamic-assignments/env-vars.yml"
    tags:
    - always

-   hosts: uat-webservers
    import_playbook: "../static-assignments/webservers.yml"

