---
-   hosts: all
    name: Include dynamic variables
    import_playbook: ../static-assiginments/common.yml
    include_vars: "../dynamic-assignments/env-vars.yml"
    tags:
    - always

-   hosts: uat-webservers
    import_playbook: ../static-assiginments/uat-webservers.yml

