---
-   name: wireshark assignments
    import_playbook: ../static-assignments/common.yml

-   name: Import dynamic variables    
    import_playbook: ../dynamic-assignments/env-vars.yml
    tags:
    - always

-   name: Webserver assignments 
    import_playbook: ../static-assignments/webservers