---
-   name: Install webserver on tooling
    import_playbook: ../static-assignments/tooling.yml

#-   name: Install mysql on database
#    import_playbook: ../static-assignments/db.yml

#-   name: wireshark assignments
#    import_playbook: ../static-assignments/common.yml#

#-   name: Import dynamic variables    
#    import_playbook: ../dynamic-assignments/env-vars.yml
#    tags:
#    - always

#-   name: Webserver assignments 
#    import_playbook: ../static-assignments/webservers.yml